config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :password], controllers:{
    sessions: 'admin/sessions'
  }
  
  
  namespace :admin do
    resources :users, only: [:index, :show, :destroy]
    
    resources :posts, only: [:index, :show, :destroy] do
      resources :post_comments, only: [:destroy]
    end
    
    resources :communities, only: [:new, :index, :show, :create, :edit, :update, :destroy]
  end
  
  scope module: :public do
    devise_for :users
    devise_scope :user do
      post 'users/guest_sign_in', to: 'sessions#guest_sign_in'
    end
    root to: "homes#top"
    
    
    resources :users, only: [:show, :index, :edit, :update, :destroy]
  
    resources :posts, only: [:show, :edit, :create, :update, :destroy] do
      resources :post_comments, only: [:create, :destroy]
    end
    
    resources :communities, only: [:new, :index, :create, :update, :edit, :destroy, :show] do
      resource :community_users, only: [:create, :destroy]
      resource :permits, only: [:create, :destroy]
    end
    
    get "communities/:id/permits" => "communities#permits", as: :permits
    
    resources :community_posts
    
    delete '/' => 'homes#delete_action'
    get '/mypage' => 'users#mypage'
    get '/search', to: 'searchs#search'
  end
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/community.rb
class Community < ApplicationRecord
  has_many :community_users, dependent: :destroy
  has_many :community_posts, dependent: :destroy
  belongs_to :owner, class_name: 'User'
  has_many :users, through: :community_users, source: :user
  has_many :permits, dependent: :destroy

  def includesUser?(user)
    community_users.exists?(user_id: user.id)
  end
  
  validates :name, presence: true
  validates :introduction, presence: true
  has_one_attached :community_image
  
  def is_owned_by?(user)
    owner.id == user.id
  end
  
  def self.looks(search, word)
    if search == "perfect_match"
      @community = Community.where("title LIKE?","#{word}")
    elsif search == "partial_match"
      @community = Community.where("title LIKE?","%#{word}%")
    else
      @community = Community.all
    end
  end
end

app/models/community_post.rb
class CommunityPost < ApplicationRecord
  has_one_attached :image
  has_one_attached :video
  
  belongs_to :user
  belongs_to :community
  
  validates :body, presence: true
end

app/models/community_user.rb
class CommunityUser < ApplicationRecord
  belongs_to :user
  belongs_to :community
  has_many :community_posts
end

app/models/permit.rb
class Permit < ApplicationRecord
  belongs_to :user
  belongs_to :community
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  has_one_attached :video
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  
  validates :body, presence: true
  
  def self.looks(search, word)
    if search == "perfect_match"
      @post = Post.where("body LIKE?","#{word}")
    elsif search == "partial_match"
      @post = Post.where("body LIKE?","%#{word}%")
    else
      @post = Post.all
    end
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
  validates :comment, presence: true  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :community_users, dependent: :destroy
  has_many :permits, dependent: :destroy
  
  validates :name, presence: true
  validates :email, presence: true
  
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end
  
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  layout 'admin'
  
  def index
    @posts = Post.all
  end
  
  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
    @user = @post.user
  end
  
  def destroy
    post = Post.find(params[:id])
    if post.destroy
      redirect_to admin_post_path, flash: {danger: "投稿を削除しました"}
    end
  end
  
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout 'admin'
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path, notice: 'ユーザーを削除しました'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_authentication
  
  private
  
  def configure_authentication
    if admin_controller?
      authenticate_admin!
    else
      authenticate_user! unless action_is_public?
    end
  end
  
  def admin_controller?
    self.class.module_parent_name == 'Admin'
  end
  
  def action_is_public?
    controller_name == 'homes' && action_name == 'top'
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/community_helper.rb
module CommunityHelper
end

app/helpers/community_posts_helper.rb
module CommunityPostsHelper
end

app/helpers/community_users_helper.rb
module CommunityUsersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/posts/index.html.erb
<div class="container p-3 text-center">
  <h2>投稿一覧</h2>
    <table class="table table-hover table-user-show">
      <thead>
        <tr>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <% @posts.each do |post| %>
      <tbody>
        <tr>
          <td>
            <%= link_to admin_post_path(post), class: 'text-dark' do %>
              <%= post.body %>
            <% end %>
          </td>
          <td>
            <% if post.image.attached? %>
              <%= image_tag url_for(post.image), size: "200x100" %>
            <% else %>
              <p></p>
            <% end %>
          </td>
          <td>
            <% if post.video.attached? %>
              <%= video_tag url_for(post.video) %>
            <% else %>
              <p></p>
            <% end %>
          </td>
          <td>
            <%= link_to "#{post.post_comments.count} コメント", admin_post_path(post.id) %>
          </td>
        </tr>
      </tbody>
      <% end %>
    </table>
</div>

app/views/admin/posts/show.html.erb
<div class="container p-3">
  <div class="row">
    <div class="col-md-4 offset-md-1">
      <h2>投稿内容</h2>

      <p><%= @user.name %></p>
  
      <p><%= @post.body %></p>
  
      <% if @post.image.attached? %>
        <h4>画像</h4>
        <%= image_tag url_for(@post.image), size: "300x200" %>
      <% else %>
      <% end %>
  
      <% if @post.video.attached? %>
        <h4>動画</h4>
        <%= video_tag url_for(@post.video) %>
        <% else %>
      <% end %>

      <%= link_to "削除する", admin_post_path(@post), method: :delete, data: { confirm: "本当に削除しますか？" }, class: 'btn btn-sm btn-danger mt-3' %>
      
    </div>
  
    <div class="col-md-3">
      <p>みんなのコメント</p>
      <% @post.post_comments.each do |post_comment| %>
        <ul>
          <li>
            <%= post_comment.user.name %>：
            <%= post_comment.comment %>
            <%= link_to "削除", admin_post_post_comment_path(post_comment.post, post_comment), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-sm btn-danger mx-2' %>
          </li>
        </ul>
      <% end %>

    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container p-3">
    <h3>全ユーザー</h3>
    <ul>
      <% @users.each do |user| %>
        <li>
          <%= link_to user.name, admin_user_path(user) %> - <%= user.email %>
          <%= link_to '削除', admin_user_path(user), method: :delete, data: { confirm: '本当に削除しますか？' } %>
        </li>
      <% end %>
    </ul>
    <h3>コミュニティ管理</h3>
    <ul>
      <li>
        <%= link_to "コミュニティ一覧を閲覧する", admin_communities_path %>
      </li>
    </ul>
    <h3>コメント管理</h3>
    <ul>
      <li>
        <%= link_to "投稿一覧を閲覧する", admin_posts_path %>
      </li>
    </ul>
</div>

app/views/admin/users/show.html.erb
<div class="container p-3">
  <div class="row">
    <div class="col-md-3">
    <h2>ユーザーページ</h2>

    <h4><%= @user.name %></h4>
    </div>
  
    <div class="col-md-8 offset-md-1">
      <h2>投稿一覧</h2>
      <table class="table table-hover table-user-show">
        <thead>
          <tr>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <% @posts.each do |post| %>
        <tbody>
          <tr>
            <td>
              <%= link_to admin_post_path(post), class: 'text-dark' do %>
                <%= post.body %>
              <% end %>
            </td>
            <td>
              <% if post.image.attached? %>
                <%= image_tag url_for(post.image), size: "300x200" %>
              <% else %>
                <p></p>
              <% end %>
            </td>
            <td>
              <% if post.video.attached? %>
                <%= video_tag url_for(post.video) %>
              <% else %>
                <p></p>
              <% end %>
            </td>
            <td>
              <%= link_to "#{post.post_comments.count} コメント", post_path(post.id) %>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container p-3">
  <h1>編集画面</h1>

  <% if @post.errors.any? %>
    <%= @post.errors.count %>件のエラーが発生しました。
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
      
  <%= form_with model: @post, method: :patch do |f| %>
  
    <h4>投稿文</h4>
    <%= f.text_area :body %>
    
    <h4>画像</h4>
    <%= f.file_field :image %>
    
    <h4>動画</h4>
    <%= f.file_field :video %>
    
    <%= f.submit '保存' %>
    
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container p-3">
  <div class="row">
    <div class="col-md-2"></div>
      <div class="col-md-6 offset-md-1">
        <h2>仲間一覧</h2>
        <table class="table">
          <thead>
            <tr>
              <th>name</th>
            </tr>
          </thead>
          <% @users.each do |user| %>
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(user) do %>
                  <%= user.name %>
                <% end %>
              </td>
            </tr>
          </tbody>
          <% end %>
      </table>
      </div>
  </div>
</div>