config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :password], controllers:{
    sessions: 'admin/sessions'
  }
  
  
  namespace :admin do
    resources :users, only: [:index, :show, :destroy]
    
    resources :posts, only: [:index, :show, :destroy] do
      resources :post_comments, only: [:destroy]
    end
    
    resources :communities, only: [:new, :index, :show, :create, :edit, :update, :destroy]
  end
  
  scope module: :public do
    devise_for :users
    devise_scope :user do
      post 'users/guest_sign_in', to: 'sessions#guest_sign_in'
    end
    root to: "homes#top"
    
    
    resources :users, only: [:show, :index, :edit, :update, :destroy]
  
    resources :posts, only: [:show, :edit, :create, :update, :destroy] do
      resources :post_comments, only: [:create, :destroy]
    end
    
    resources :communities, only: [:new, :index, :create, :update, :edit, :destroy, :show] do
      resource :community_users, only: [:create, :destroy]
      resource :permits, only: [:create, :destroy]
    end
    
    get "communities/:id/permits" => "communities#permits", as: :permits
    
    resources :community_posts
    
    delete '/' => 'homes#delete_action'
    get '/mypage' => 'users#mypage'
    get '/search', to: 'searchs#search'
  end
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/community.rb
class Community < ApplicationRecord
  has_many :community_users, dependent: :destroy
  has_many :community_posts, dependent: :destroy
  belongs_to :owner, class_name: 'User'
  has_many :users, through: :community_users, source: :user
  has_many :permits, dependent: :destroy

  def includesUser?(user)
    community_users.exists?(user_id: user.id)
  end
  
  validates :name, presence: true
  validates :introduction, presence: true
  has_one_attached :community_image
  
  def is_owned_by?(user)
    owner.id == user.id
  end
  
  def self.looks(search, word)
    if search == "perfect_match"
      @community = Community.where("title LIKE?","#{word}")
    elsif search == "partial_match"
      @community = Community.where("title LIKE?","%#{word}%")
    else
      @community = Community.all
    end
  end
end

app/models/community_post.rb
class CommunityPost < ApplicationRecord
  has_one_attached :image
  has_one_attached :video
  
  belongs_to :user
  belongs_to :community
  
  validates :body, presence: true
end

app/models/community_user.rb
class CommunityUser < ApplicationRecord
  belongs_to :user
  belongs_to :community
  has_many :community_posts
end

app/models/permit.rb
class Permit < ApplicationRecord
  belongs_to :user
  belongs_to :community
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  has_one_attached :video
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  
  validates :body, presence: true
  
  def self.looks(search, word)
    if search == "perfect_match"
      @post = Post.where("body LIKE?","#{word}")
    elsif search == "partial_match"
      @post = Post.where("body LIKE?","%#{word}%")
    else
      @post = Post.all
    end
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
  validates :comment, presence: true  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :community_users, dependent: :destroy
  has_many :permits, dependent: :destroy
  
  validates :name, presence: true
  validates :email, presence: true
  
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end
  
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
end

app/controllers/admin/communities_controller.rb
class Admin::CommunitiesController < ApplicationController
  layout 'admin'
  
  
  def index
    @communities = Community.all
  end
  
  def show
    @communities = Community.find(params[:id])
    @user = User.find(params[:id])
  end
  
  def create
    @community = Community.new(community_params)
    @community.admin_id = current_admin.id
    if @community.save
      redirect_to admin_communities_path
    else
      render 'new'
    end
  end
  
  def edit
    
  end
  
  def update
    if @community.update(community_params)
      redirect_to admin_communities_path
    else
      render 'edit'
    end
  end
  
  def destroy
    @community = Community.find(params[:id])
    @community.destroy
    redirect_to admin_communities_path, flash: {danger: "コミュニティを削除しました"}
  end
  
  private
  
  def community_params
    params.require(:community).permit(:name, :introduction, :community_image)
  end
  
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  layout 'admin'
  
  def index
    @posts = Post.all
  end
  
  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
    @user = @post.user
  end
  
  def destroy
    post = Post.find(params[:id])
    if post.destroy
      redirect_to admin_post_path, flash: {danger: "投稿を削除しました"}
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_authentication
  
  private
  
  def configure_authentication
    if admin_controller?
      authenticate_admin!
    else
      authenticate_user! unless action_is_public?
    end
  end
  
  def admin_controller?
    self.class.module_parent_name == 'Admin'
  end
  
  def action_is_public?
    controller_name == 'homes' && action_name == 'top'
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/community_helper.rb
module CommunityHelper
end

app/helpers/community_posts_helper.rb
module CommunityPostsHelper
end

app/helpers/community_users_helper.rb
module CommunityUsersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/communities/_form.html.erb
<%= form_with model: community, local: true do |f| %>
  <div class="form-group">
    <%= f.label :コミュニティ名 %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :紹介文 %>
    <%= f.text_area :introduction, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :グループ画像 %>
    <%= f.file_field :community_image, class: "form-control-file" , accept: "image/*" %>
  </div>

  <div class="form-group">
    <%= f.submit class: 'btn btn-info' %>
  </div>
<% end %>

app/views/admin/communities/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th></th>
      <th>コミュニティ名</th>
      <th>紹介文</th>
      <th>参加人数</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% communities.each do |community| %>
      <tr>
        <td>
          <% if community.community_image.attached? %>
            <%= image_tag community.community_image,size:"75x50" %>
          <% else %>
          <% end %>
        </td>
        <td>
          <%= community.name %>
        </td>
        <td>
          <%= community.introduction %>
        </td>
        <td>
          <%= community.community_users.count %>
        </td>
        <td>
          <%= link_to '削除', admin_community_path(community), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "btn btn-sm btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table> 

app/views/admin/communities/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3>コミュニティ編集</h3>
        <%= render 'form', community: @community %>
  </div>
</div>

app/views/admin/communities/index.html.erb
<div class='container p-3 text-center'>
  <h2>コミュニティ一覧</h2>
    <%= render 'index', communities: @communities %>
</div>

app/views/admin/communities/new.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3>コミュニティ作成</h3>
        <%= form_with(model: @community) do |f| %>
          <div class="form-group">
            <%= f.label :コミュニティ名 %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :紹介文 %>
            <%= f.text_area :introduction, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :グループ画像 %>
            <%= f.file_field :community_image, class: "form-control-file" , accept: "image/*" %>
          </div>

          <div class="form-group">
            <%= f.submit class: 'btn btn-info' %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/admin/communities/show.html.erb
<div class='container px-5 px-sm-0'>
<%= flash[:notice] %>
  <div class='row'>
    <div class='col-md-3'>
    
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>コミュニティ詳細</h2>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>コミュニティ名</th>
            <th>紹介文</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <% if @group.group_image.attached? %>
                <%= image_tag @group.group_image,size:"50x50" %>
              <% else %>
                <%= image_tag 'no_image', size: "50x50" %>
              <% end %>
            </td>
            </td>
            <td><%= @group.name %></td>
            <td><%= @group.introduction %></td>
            <td>
              <% if @group.owner_id == current_user.id %>
                <%= link_to 'Edit', edit_group_path(@group), class: "btn btn-sm btn-success" %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>