config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :password], controllers:{
    sessions: 'admin/sessions'
  }
  
  
  namespace :admin do
    resources :users, only: [:index, :show, :destroy]
    
    resources :posts, only: [:index, :show, :destroy] do
      resources :post_comments, only: [:destroy]
    end
    
    resources :communities, only: [:new, :index, :show, :create, :edit, :update, :destroy]
  end
  
  scope module: :public do
    devise_for :users
    devise_scope :user do
      post 'users/guest_sign_in', to: 'sessions#guest_sign_in'
    end
    root to: "homes#top"
    
    
    resources :users, only: [:show, :index, :edit, :update, :destroy]
  
    resources :posts, only: [:show, :edit, :create, :update, :destroy] do
      resources :post_comments, only: [:create, :destroy]
    end
    
    resources :communities, only: [:new, :index, :create, :update, :edit, :destroy, :show] do
      resource :community_users, only: [:create, :destroy]
      resource :permits, only: [:create, :destroy]
    end
    
    get "communities/:id/permits" => "communities#permits", as: :permits
    
    resources :community_posts
    
    delete '/' => 'homes#delete_action'
    get '/mypage' => 'users#mypage'
    get '/search', to: 'searchs#search'
  end
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/community.rb
class Community < ApplicationRecord
  has_many :community_users, dependent: :destroy
  has_many :community_posts, dependent: :destroy
  belongs_to :owner, class_name: 'User'
  has_many :users, through: :community_users, source: :user
  has_many :permits, dependent: :destroy

  def includesUser?(user)
    community_users.exists?(user_id: user.id)
  end
  
  validates :name, presence: true
  validates :introduction, presence: true
  has_one_attached :community_image
  
  def is_owned_by?(user)
    owner.id == user.id
  end
  
  def self.looks(search, word)
    if search == "perfect_match"
      @community = Community.where("title LIKE?","#{word}")
    elsif search == "partial_match"
      @community = Community.where("title LIKE?","%#{word}%")
    else
      @community = Community.all
    end
  end
end

app/models/community_post.rb
class CommunityPost < ApplicationRecord
  has_one_attached :image
  has_one_attached :video
  
  belongs_to :user
  belongs_to :community
  
  validates :body, presence: true
end

app/models/community_user.rb
class CommunityUser < ApplicationRecord
  belongs_to :user
  belongs_to :community
  has_many :community_posts
end

app/models/permit.rb
class Permit < ApplicationRecord
  belongs_to :user
  belongs_to :community
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  has_one_attached :video
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  
  validates :body, presence: true
  
  def self.looks(search, word)
    if search == "perfect_match"
      @post = Post.where("body LIKE?","#{word}")
    elsif search == "partial_match"
      @post = Post.where("body LIKE?","%#{word}%")
    else
      @post = Post.all
    end
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
  validates :comment, presence: true  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :community_users, dependent: :destroy
  has_many :permits, dependent: :destroy
  
  validates :name, presence: true
  validates :email, presence: true
  
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end
  
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_authentication
  
  private
  
  def configure_authentication
    if admin_controller?
      authenticate_admin!
    else
      authenticate_user! unless action_is_public?
    end
  end
  
  def admin_controller?
    self.class.module_parent_name == 'Admin'
  end
  
  def action_is_public?
    controller_name == 'homes' && action_name == 'top'
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/community_helper.rb
module CommunityHelper
end

app/helpers/community_posts_helper.rb
module CommunityPostsHelper
end

app/helpers/community_users_helper.rb
module CommunityUsersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "新規登録", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワードをお忘れですか？", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "確認の手順が届きませんか？", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "ロック解除の手順が届きませんか?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>Admin-gametoshare</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/37b4bbcd03.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'date-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg bg-dark">
        <div class="cantainer">
          <% if admin_signed_in? %>
          <a class="navbar-brand p-3 text-light" href="/admin/users">
            <strong>
              <i class="fa-brands fa-phoenix-framework"></i>
              <span>GAME to Share</span>
            </strong>
          </a>
          <% else %>
          <a class="navbar-brand p-3 text-light" href="/">
            <strong>
              <i class="fa-brands fa-phoenix-framework"></i>
              <span>GAME to Share</span>
            </strong>
          </a>
          <% end %>
          <% if admin_signed_in? %>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
              aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav">
                <li class="nav-item btn btn-sm btn-outline-light">
                  <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'text-light' %>
                </li>
                <li class="nav-item btn btn-sm btn-outline-light">
                  <%= link_to 'ユーザー', admin_users_path, class: 'text-light' %>
                </li>
                <li class="nav-item btn btn-sm btn-outline-light">
                  <%= link_to 'コミュニティ', admin_communities_path, class: 'text-light' %>
                </li>
                <li class="nav-item btn btn-sm btn-outline-light">
                  <%= link_to '投稿', admin_posts_path, class: 'text-light' %>
                </li>
              </ul>
            </div>
          <% end %>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gametoshare</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/37b4bbcd03.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'date-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header>
      <nav class="navbar navbar-expand-lg bg-danger ">
        <div class="container-fluid">
          <% if user_signed_in? %>
          <a class="navbar-brand p-3 text-dark" href="/mypage">
            <strong>
              <i class="fa-brands fa-phoenix-framework"></i>
              <span>GAMEtoShare</span>
            </strong>
          </a>
          <% else %>
          <a class="navbar-brand p-3 text-dark" href="/admin/sign_in">
            <strong>
              <i class="fa-brands fa-phoenix-framework"></i>
              <span>GAMEtoShare</span>
            </strong>
          </a>
          <% end %>
          
          <button class="navbar-toggler bg-light" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fa-solid fa-bars"></i>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <% if user_signed_in? %>
              <ul class="navbar-nav">
                <li class="nav-item">
                  <%= link_to "マイページ", '/mypage', class: 'nav-link bg-light text-dark btn btn-outline-danger btn-sm px-1 mx-1' %>
                </li>
                <li class="nav-item">
                  <%= link_to "友達一覧", users_path, class: 'nav-link bg-light text-dark btn btn-outline-danger btn-sm px-1 mx-1' %>
                </li>
                <li class="nav-item">
                  <%= link_to "コミュニティ一覧", communities_path, class: 'nav-link bg-light text-dark btn btn-outline-danger btn-sm px-1 mx-1' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link bg-light text-dark btn btn-outline-danger btn-sm px-1 mx-1' %>
                </li>
              </ul>
            <% else %>
              <ul class="navbar-nav">
                <li class="nav-item">
                  <%= link_to "トップ", "/", class: 'nav-link bg-light text-dark btn btn-outline-danger btn-sm px-1 mx-1' %>
                </li>
                <li class="nav-item">
                  <%= link_to "新規登録", new_user_registration_path, class: 'nav-link bg-light text-dark btn btn-outline-danger btn-sm px-1 mx-1' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログイン", new_user_session_path, class: 'nav-link bg-light text-dark btn btn-outline-danger btn-sm px-1 mx-1' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ゲストログイン", users_guest_sign_in_path, method: :post, class: 'nav-link bg-light text-dark btn btn-outline-danger btn-sm px-1 mx-1' %>
                </li>
              </ul>
            <% end %>
          </div>
          
          <% if user_signed_in? %>
          <div class="m-2">
            <%= render 'public/searchs/form' %>
          </div>
          <% else %>
          <% end %>
          
        </div>
      </nav>
    </header>
    <main class="mb-auto">
      <div class="container-fluid pt-2">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>" role="alert">
            <%= message %><button type="button" class="close" data-dismiss="alert">&times;</button>
          </div>
        <% end %>
      </div>
      <%= yield %>
    </main>
    <footer class="bg-danger">
      <div class='container'>
        <div class='row'>
          <div class='mx-auto text-dark'>
    　      <p>Copyright © sample All Rights Reserved.</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>